// Code generated by qtc from "index.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/index.qtpl:1
package templates

//line templates/index.qtpl:1
import "test1/models"

//line templates/index.qtpl:2
import "encoding/json"

//line templates/index.qtpl:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/index.qtpl:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/index.qtpl:4
func StreamCode(qw422016 *qt422016.Writer, data models.Objects) {
//line templates/index.qtpl:4
	qw422016.N().S(`
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Database</title>
</head>
<body>
	`)
//line templates/index.qtpl:13
	for _, object := range data {
//line templates/index.qtpl:13
		qw422016.N().S(`
		`)
//line templates/index.qtpl:14
		u, _ := json.Marshal(object.ID)

//line templates/index.qtpl:14
		qw422016.N().S(`
		`)
//line templates/index.qtpl:15
		qw422016.E().Z(u)
//line templates/index.qtpl:15
		qw422016.N().S(`
		`)
//line templates/index.qtpl:16
		d := object.Data.Bytes

//line templates/index.qtpl:16
		qw422016.N().S(`
		`)
//line templates/index.qtpl:17
		qw422016.E().Z(d)
//line templates/index.qtpl:17
		qw422016.N().S(`
		<br>
		<br>
	`)
//line templates/index.qtpl:20
	}
//line templates/index.qtpl:20
	qw422016.N().S(`
</body>
</html>
`)
//line templates/index.qtpl:23
}

//line templates/index.qtpl:23
func WriteCode(qq422016 qtio422016.Writer, data models.Objects) {
//line templates/index.qtpl:23
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/index.qtpl:23
	StreamCode(qw422016, data)
//line templates/index.qtpl:23
	qt422016.ReleaseWriter(qw422016)
//line templates/index.qtpl:23
}

//line templates/index.qtpl:23
func Code(data models.Objects) string {
//line templates/index.qtpl:23
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/index.qtpl:23
	WriteCode(qb422016, data)
//line templates/index.qtpl:23
	qs422016 := string(qb422016.B)
//line templates/index.qtpl:23
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/index.qtpl:23
	return qs422016
//line templates/index.qtpl:23
}
